/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import java.awt.event.MouseEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Cart extends javax.swing.JFrame {

    /**
     * Creates new form Cart
     */
    public Cart() {
        initComponents();
    }
     private void showPopUp(MouseEvent e){
        popupmenu.show(this,e.getX(), e.getY());
        
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupmenu = new javax.swing.JPopupMenu();
        mbtnprofile = new javax.swing.JMenuItem();
        mbtnhome = new javax.swing.JMenuItem();
        mbtnlogout = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        subtotal = new javax.swing.JLabel();
        rs = new javax.swing.JLabel();
        dining = new javax.swing.JLabel();
        packing = new javax.swing.JLabel();
        btnplaceorder = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        coupon = new javax.swing.JTextField();
        btnapply = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mhome = new javax.swing.JMenuItem();

        popupmenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        popupmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                popupmenuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                popupmenuMouseReleased(evt);
            }
        });

        mbtnprofile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mbtnprofile.setForeground(new java.awt.Color(204, 153, 0));
        mbtnprofile.setText("Profile");
        mbtnprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtnprofileActionPerformed(evt);
            }
        });
        popupmenu.add(mbtnprofile);

        mbtnhome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mbtnhome.setForeground(new java.awt.Color(204, 153, 0));
        mbtnhome.setText("Home");
        mbtnhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtnhomeActionPerformed(evt);
            }
        });
        popupmenu.add(mbtnhome);

        mbtnlogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mbtnlogout.setForeground(new java.awt.Color(204, 153, 0));
        mbtnlogout.setText("Logout");
        mbtnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mbtnlogoutActionPerformed(evt);
            }
        });
        popupmenu.add(mbtnlogout);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MY CART");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 60, 169, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 20, 109, 110));

        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, 160));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBackground(new java.awt.Color(255, 153, 102));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(129, 102, 132));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "S.No.", "Items", "Quantity", "Price", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(153, 102, 0));
        jTable1.setSelectionBackground(new java.awt.Color(204, 102, 0));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 630, 350));

        subtotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subtotal.setForeground(new java.awt.Color(255, 255, 255));
        subtotal.setText("Total Amount:");
        getContentPane().add(subtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 620, 110, 31));

        rs.setBackground(new java.awt.Color(255, 255, 255));
        rs.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rs.setForeground(new java.awt.Color(255, 255, 255));
        rs.setText("Rs");
        getContentPane().add(rs, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 620, 20, 30));

        dining.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dining.setText("d");
        getContentPane().add(dining, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 54, -1));

        packing.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        packing.setText("p");
        getContentPane().add(packing, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, 54, -1));

        btnplaceorder.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnplaceorder.setForeground(new java.awt.Color(255, 0, 102));
        btnplaceorder.setText("Place Order");
        btnplaceorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplaceorderActionPerformed(evt);
            }
        });
        getContentPane().add(btnplaceorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 450, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("Packing");
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 98, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setSelected(true);
        jRadioButton2.setText("Dining");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 98, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Apply Coupon :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 580, 120, 30));
        getContentPane().add(coupon, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 580, 300, 30));

        btnapply.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnapply.setForeground(new java.awt.Color(153, 0, 51));
        btnapply.setText("Apply ");
        getContentPane().add(btnapply, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 580, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 620, 260, 20));

        jMenu1.setText("^");
        jMenu1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 24)); // NOI18N

        mhome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mhome.setForeground(new java.awt.Color(204, 153, 0));
        mhome.setText("Home");
        mhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mhomeActionPerformed(evt);
            }
        });
        jMenu1.add(mhome);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void popupmenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popupmenuMousePressed
        // TODO add your handling code here:
         
    }//GEN-LAST:event_popupmenuMousePressed

    private void popupmenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popupmenuMouseReleased
        // TODO add your handling code here:
         
    }//GEN-LAST:event_popupmenuMouseReleased

    private void mhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mhomeActionPerformed
        // TODO add your handling code here:
         HomePage hForm = new HomePage();
                hForm.setVisible(true);
                dispose(); 
    }//GEN-LAST:event_mhomeActionPerformed

    private void mbtnprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtnprofileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mbtnprofileActionPerformed

    private void mbtnhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtnhomeActionPerformed
        // TODO add your handling code here:
        HomePage hForm = new HomePage();
                hForm.setVisible(true);
                dispose(); 
    }//GEN-LAST:event_mbtnhomeActionPerformed

    private void mbtnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mbtnlogoutActionPerformed
        // TODO add your handling code here:
        User_Login loginForm = new User_Login();
                loginForm.setVisible(true);
                dispose(); 
    }//GEN-LAST:event_mbtnlogoutActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        if(evt.isPopupTrigger()){
            showPopUp(evt);}
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        // TODO add your handling code here:
        if(evt.isPopupTrigger()){
            showPopUp(evt);}
    }//GEN-LAST:event_formMouseReleased

    private void btnplaceorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplaceorderActionPerformed
        // TODO add your handling code here:
        int a =JOptionPane.showConfirmDialog(null,"Do you really want to place the order","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
            ImageIcon icon=new ImageIcon("src/images/Screenshot_13-11-2024_143330_.jpeg");
            JOptionPane.showMessageDialog(null,"<html><b>Your Order Is Confirmed!</b></html>","Message",JOptionPane.INFORMATION_MESSAGE,icon);
        }
    }//GEN-LAST:event_btnplaceorderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnapply;
    private javax.swing.JButton btnplaceorder;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField coupon;
    private javax.swing.JLabel dining;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenuItem mbtnhome;
    private javax.swing.JMenuItem mbtnlogout;
    private javax.swing.JMenuItem mbtnprofile;
    private javax.swing.JMenuItem mhome;
    private javax.swing.JLabel packing;
    private javax.swing.JPopupMenu popupmenu;
    private javax.swing.JLabel rs;
    private javax.swing.JLabel subtotal;
    // End of variables declaration//GEN-END:variables
}
