/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import java.awt.event.MouseEvent;

/**
 *
 * @author soumitra
 */
public class CombosSpecials extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public CombosSpecials() {
        initComponents();
    }
//    private void ShowPopMenu (MouseEvent e){
//        PopMenu.sho
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopMenu = new javax.swing.JMenu();
        Orders = new javax.swing.JMenuItem();
        Profile = new javax.swing.JMenuItem();
        Checkout = new javax.swing.JMenuItem();
        Logout = new javax.swing.JMenuItem();
        HomeButton = new javax.swing.JButton();
        SnacksButton = new javax.swing.JButton();
        HelloLabel = new javax.swing.JLabel();
        DrinksButton = new javax.swing.JButton();
        ComboSpecialButton = new javax.swing.JButton();
        UserNameLabel = new javax.swing.JLabel();
        TaglineLabel = new javax.swing.JLabel();
        IconLabel = new javax.swing.JLabel();
        CouponsScrollPane = new javax.swing.JScrollPane();
        Drinks = new javax.swing.JTable();
        UserMenu = new javax.swing.JButton();

        PopMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Profile.jpeg"))); // NOI18N
        PopMenu.setInheritsPopupMenu(true);
        PopMenu.setOpaque(true);
        PopMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PopMenuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                PopMenuMouseReleased(evt);
            }
        });

        Orders.setText("Orders");
        Orders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OrdersMouseClicked(evt);
            }
        });
        Orders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdersActionPerformed(evt);
            }
        });
        PopMenu.add(Orders);

        Profile.setText("Profile");
        Profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProfileMouseClicked(evt);
            }
        });
        Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileActionPerformed(evt);
            }
        });
        PopMenu.add(Profile);

        Checkout.setText("Checkout/ Cart");
        Checkout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckoutMouseClicked(evt);
            }
        });
        PopMenu.add(Checkout);

        Logout.setText("Logout");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        PopMenu.add(Logout);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        HomeButton.setText("Home");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        SnacksButton.setText("Snacks");
        SnacksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SnacksButtonActionPerformed(evt);
            }
        });

        HelloLabel.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        HelloLabel.setText("Hello");

        DrinksButton.setText("Drinks");
        DrinksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DrinksButtonActionPerformed(evt);
            }
        });

        ComboSpecialButton.setText("Combos & Specials");
        ComboSpecialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboSpecialButtonActionPerformed(evt);
            }
        });

        UserNameLabel.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        UserNameLabel.setText("User!");

        TaglineLabel.setText("Nice Tagline 101!!!");

        IconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        Drinks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Drink 1", null},
                {"Drink 2", null},
                {"Drink 3", null},
                {"Drink 4", null},
                {"Drink 5", null},
                {"Drink 6", null},
                {"Drink 7", null},
                {"Drink 8", null},
                {"Drink 9", null},
                {"Drink 10", null}
            },
            new String [] {
                "Combos and Specials", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CouponsScrollPane.setViewportView(Drinks);

        UserMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Profile.jpeg"))); // NOI18N
        UserMenu.setInheritsPopupMenu(true);
        UserMenu.setMaximumSize(new java.awt.Dimension(180, 180));
        UserMenu.setMinimumSize(new java.awt.Dimension(180, 180));
        UserMenu.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(IconLabel)
                        .addGap(59, 59, 59)
                        .addComponent(TaglineLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(HomeButton)
                        .addGap(68, 68, 68)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(HelloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DrinksButton)
                                .addGap(100, 100, 100)
                                .addComponent(ComboSpecialButton)
                                .addContainerGap(285, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(UserNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(UserMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(SnacksButton)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CouponsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UserNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HelloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(TaglineLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(IconLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(UserMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomeButton)
                    .addComponent(SnacksButton)
                    .addComponent(DrinksButton)
                    .addComponent(ComboSpecialButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(CouponsScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfileActionPerformed

    private void OrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OrdersActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void SnacksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SnacksButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SnacksButtonActionPerformed

    private void DrinksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DrinksButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DrinksButtonActionPerformed

    private void ComboSpecialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboSpecialButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboSpecialButtonActionPerformed

    private void PopMenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PopMenuMousePressed
        // TODO add your handling code here:
        if(evt.isPopupTrigger()){
//            UserMenuPopUp(evt);
        }
    }//GEN-LAST:event_PopMenuMousePressed

    private void PopMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PopMenuMouseReleased
        // TODO add your handling code here:
        if(evt.isPopupTrigger()){
//            UserMenuPopUp(evt);
        }
    }//GEN-LAST:event_PopMenuMouseReleased

    private void ProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProfileMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ProfileMouseClicked

    private void OrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OrdersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_OrdersMouseClicked

    private void CheckoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckoutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckoutMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutMouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CombosSpecials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CombosSpecials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CombosSpecials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CombosSpecials.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CombosSpecials().setVisible(true);
//                new UserPopUpMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Checkout;
    private javax.swing.JButton ComboSpecialButton;
    private javax.swing.JScrollPane CouponsScrollPane;
    private javax.swing.JTable Drinks;
    private javax.swing.JButton DrinksButton;
    private javax.swing.JLabel HelloLabel;
    private javax.swing.JButton HomeButton;
    private javax.swing.JLabel IconLabel;
    private javax.swing.JMenuItem Logout;
    private javax.swing.JMenuItem Orders;
    private javax.swing.JMenu PopMenu;
    private javax.swing.JMenuItem Profile;
    private javax.swing.JButton SnacksButton;
    private javax.swing.JLabel TaglineLabel;
    private javax.swing.JButton UserMenu;
    private javax.swing.JLabel UserNameLabel;
    // End of variables declaration//GEN-END:variables
}
