/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cafe.management.system;

import dao.ItemDao;
import dao.UserDao;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import model.Item;
import model.User;

/**
 *
 * @author soumitra
 */
public class HomePage extends javax.swing.JFrame {
    
    private int currentPanelIndex = 0;


    /**
     * Creates new form HomePage
     */
    private String email="user@gmail.com";
    public HomePage() {
        initComponents();
    }
     public HomePage(String email) {
         this.email=email;
        initComponents();
    }
    
    private void showPopUp(MouseEvent e){
        popup.show(this,btnusermenu.getX()+(2*(btnusermenu.getWidth())),btnusermenu.getY()+((btnusermenu.getHeight())));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup = new javax.swing.JPopupMenu();
        mprofile = new javax.swing.JMenuItem();
        HelloLabel = new javax.swing.JLabel();
        UserNameLabel = new javax.swing.JLabel();
        TaglineLabel = new javax.swing.JLabel();
        IconLabel = new javax.swing.JLabel();
        btnusermenu = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();
        pdrinks = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tDrinks = new javax.swing.JTable();
        psnacks = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tSnacks = new javax.swing.JTable();
        pcombo = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tCombos = new javax.swing.JTable();
        poffers = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        layeredPane = new javax.swing.JLayeredPane();
        p2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        p1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        p3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        p4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        p5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        btnbackward = new javax.swing.JButton();
        btnforward = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mgotocart = new javax.swing.JMenuItem();
        mlogout = new javax.swing.JMenuItem();

        mprofile.setBackground(new java.awt.Color(204, 204, 204));
        mprofile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mprofile.setForeground(new java.awt.Color(255, 102, 102));
        mprofile.setText("Profile     ");
        mprofile.setBorder(null);
        mprofile.setPreferredSize(new java.awt.Dimension(150, 42));
        mprofile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mprofileActionPerformed(evt);
            }
        });
        popup.add(mprofile);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HelloLabel.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        HelloLabel.setText("Hello");
        getContentPane().add(HelloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 141, 67));

        UserNameLabel.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        UserNameLabel.setText("User!");
        getContentPane().add(UserNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 151, 78));

        TaglineLabel.setText("Nice Tagline 101!!!");
        getContentPane().add(TaglineLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, -1, -1));
        getContentPane().add(IconLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        btnusermenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Profile.jpeg"))); // NOI18N
        btnusermenu.setInheritsPopupMenu(true);
        btnusermenu.setMaximumSize(new java.awt.Dimension(180, 180));
        btnusermenu.setMinimumSize(new java.awt.Dimension(180, 180));
        btnusermenu.setOpaque(true);
        btnusermenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnusermenuMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnusermenuMouseReleased(evt);
            }
        });
        btnusermenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusermenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnusermenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 20, 90, 110));

        tabbedPane.setBackground(new java.awt.Color(255, 153, 153));
        tabbedPane.setForeground(new java.awt.Color(255, 255, 255));
        tabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tabbedPane.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tabbedPane.setMinimumSize(new java.awt.Dimension(225, 137));

        pdrinks.setBackground(new java.awt.Color(255, 204, 0));
        pdrinks.setForeground(new java.awt.Color(255, 153, 153));
        pdrinks.setMinimumSize(new java.awt.Dimension(225, 80));
        pdrinks.setPreferredSize(new java.awt.Dimension(225, 80));
        pdrinks.setLayout(new java.awt.BorderLayout());

        tDrinks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No.", "Item Name", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tDrinks);
        if (tDrinks.getColumnModel().getColumnCount() > 0) {
            tDrinks.getColumnModel().getColumn(0).setMinWidth(100);
            tDrinks.getColumnModel().getColumn(0).setPreferredWidth(100);
            tDrinks.getColumnModel().getColumn(0).setMaxWidth(200);
        }

        pdrinks.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        tabbedPane.addTab("Drinks", pdrinks);

        psnacks.setBackground(new java.awt.Color(204, 204, 0));
        psnacks.setMinimumSize(new java.awt.Dimension(225, 80));
        psnacks.setPreferredSize(new java.awt.Dimension(225, 80));
        psnacks.setLayout(new java.awt.BorderLayout());

        tSnacks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No.", "Item Name", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tSnacks);
        if (tSnacks.getColumnModel().getColumnCount() > 0) {
            tSnacks.getColumnModel().getColumn(0).setMinWidth(100);
            tSnacks.getColumnModel().getColumn(0).setPreferredWidth(100);
            tSnacks.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        psnacks.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        tabbedPane.addTab("Snacks", psnacks);

        pcombo.setBackground(new java.awt.Color(255, 204, 102));
        pcombo.setMinimumSize(new java.awt.Dimension(225, 80));
        pcombo.setPreferredSize(new java.awt.Dimension(225, 80));
        pcombo.setLayout(new java.awt.BorderLayout());

        tCombos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S.No.", "Item Name", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tCombos);
        if (tCombos.getColumnModel().getColumnCount() > 0) {
            tCombos.getColumnModel().getColumn(0).setMinWidth(100);
            tCombos.getColumnModel().getColumn(0).setPreferredWidth(100);
            tCombos.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        pcombo.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        tabbedPane.addTab("Combo Special", pcombo);

        poffers.setBackground(new java.awt.Color(255, 204, 153));
        poffers.setForeground(new java.awt.Color(255, 255, 255));
        poffers.setMinimumSize(new java.awt.Dimension(225, 80));
        poffers.setName(""); // NOI18N
        poffers.setPreferredSize(new java.awt.Dimension(225, 80));

        jLabel7.setBackground(new java.awt.Color(204, 153, 255));
        jLabel7.setText("OFFER0");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 153, 255), 4, true));

        jLabel8.setText("OFFER1");
        jLabel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 51, 255), 4, true));

        jLabel9.setText("OFFER2");
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 204), 4, true));

        javax.swing.GroupLayout poffersLayout = new javax.swing.GroupLayout(poffers);
        poffers.setLayout(poffersLayout);
        poffersLayout.setHorizontalGroup(
            poffersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(poffersLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(poffersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(235, 235, 235))
        );
        poffersLayout.setVerticalGroup(
            poffersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(poffersLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 225, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Offers & Coupons", poffers);

        getContentPane().add(tabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 180, 760, 570));

        layeredPane.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 102, 102)));
        layeredPane.setLayout(new javax.swing.OverlayLayout(layeredPane));

        p2.setMinimumSize(new java.awt.Dimension(462, 259));
        p2.setPreferredSize(new java.awt.Dimension(462, 259));
        p2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setText("special snacks");
        p2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 6, -1, -1));

        p1.setMinimumSize(new java.awt.Dimension(462, 259));
        p1.setPreferredSize(new java.awt.Dimension(462, 259));
        p1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("special drinks");
        p1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 135, -1, -1));

        jButton2.setForeground(new java.awt.Color(102, 0, 102));
        jButton2.setText("Add me+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        p1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 110, 30));

        p2.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 534, 484));
        p1.getAccessibleContext().setAccessibleName("");

        layeredPane.add(p2);

        p3.setMinimumSize(new java.awt.Dimension(462, 259));
        p3.setPreferredSize(new java.awt.Dimension(462, 259));
        p3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("special combos");
        p3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 5, -1, -1));

        jButton3.setForeground(new java.awt.Color(102, 0, 102));
        jButton3.setText("add me");
        p3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 230, -1, -1));

        layeredPane.add(p3);

        p4.setMinimumSize(new java.awt.Dimension(462, 259));
        p4.setPreferredSize(new java.awt.Dimension(462, 259));
        p4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel4.setText("meal of the day");
        p4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 5, -1, -1));

        jButton4.setForeground(new java.awt.Color(102, 0, 102));
        jButton4.setText("add me");
        p4.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 230, -1, -1));

        layeredPane.add(p4);

        p5.setMinimumSize(new java.awt.Dimension(462, 259));
        p5.setPreferredSize(new java.awt.Dimension(462, 259));
        p5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel5.setText("fussion dessert");
        p5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 5, -1, -1));

        jButton5.setForeground(new java.awt.Color(102, 0, 102));
        jButton5.setText("add me");
        p5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 230, -1, -1));

        layeredPane.add(p5);

        getContentPane().add(layeredPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 540, 490));

        btnbackward.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnbackward.setText("<");
        btnbackward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackwardActionPerformed(evt);
            }
        });
        getContentPane().add(btnbackward, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        btnforward.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        btnforward.setText(">");
        btnforward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnforwardActionPerformed(evt);
            }
        });
        getContentPane().add(btnforward, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, -1, -1));

        jMenu1.setText("\\/");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        mgotocart.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mgotocart.setForeground(new java.awt.Color(255, 153, 51));
        mgotocart.setText("Go to Cart");
        mgotocart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mgotocartActionPerformed(evt);
            }
        });
        jMenu1.add(mgotocart);

        mlogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mlogout.setForeground(new java.awt.Color(255, 153, 0));
        mlogout.setText("Logout");
        mlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mlogoutActionPerformed(evt);
            }
        });
        jMenu1.add(mlogout);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    private void btnusermenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusermenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnusermenuActionPerformed

    private void mgotocartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mgotocartActionPerformed
        // TODO add your handling code here:
        Cart cart = new Cart();
                cart.setVisible(true);
                dispose(); 
    }//GEN-LAST:event_mgotocartActionPerformed

    private void btnusermenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnusermenuMousePressed
        // TODO add your handling code here:
        if(evt.isPopupTrigger()){
            showPopUp(evt);}
    }//GEN-LAST:event_btnusermenuMousePressed

    private void btnusermenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnusermenuMouseReleased
        // TODO add your handling code here:
        if(evt.isPopupTrigger()){
            showPopUp(evt);}
    }//GEN-LAST:event_btnusermenuMouseReleased
    
    private void btnforwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnforwardActionPerformed
        // TODO add your handling code here:
        currentPanelIndex = (currentPanelIndex + 1) % 5;

    // Set the layer indices
    if (currentPanelIndex == 0) {
        layeredPane.setLayer(p1, 0);
        layeredPane.setLayer(p2, -1);
        layeredPane.setLayer(p3, -1);
        layeredPane.setLayer(p4, -1);
        layeredPane.setLayer(p5, -1);
    } else if (currentPanelIndex == 1) {
        layeredPane.setLayer(p1, -1);
        layeredPane.setLayer(p2, 0);
        layeredPane.setLayer(p3, -1);
        layeredPane.setLayer(p4, -1);
        layeredPane.setLayer(p5, -1);
    } else if (currentPanelIndex == 2) {
        layeredPane.setLayer(p1, -1);
        layeredPane.setLayer(p2, -1);
        layeredPane.setLayer(p3, 0);
        layeredPane.setLayer(p4, -1);
        layeredPane.setLayer(p5, -1);
    } else if (currentPanelIndex == 3) {
        layeredPane.setLayer(p1, -1);
        layeredPane.setLayer(p2, -1);
        layeredPane.setLayer(p3, -1);
        layeredPane.setLayer(p4, 0);
        layeredPane.setLayer(p5, -1);
    } else if (currentPanelIndex == 4) {
        layeredPane.setLayer(p1, -1);
        layeredPane.setLayer(p2, -1);
        layeredPane.setLayer(p3, -1);
        layeredPane.setLayer(p4, -1);
        layeredPane.setLayer(p5, 0);
    }



    }//GEN-LAST:event_btnforwardActionPerformed

    private void btnbackwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackwardActionPerformed
        // TODO add your handling code here:
         currentPanelIndex = (currentPanelIndex - 1 + 5) % 5;

    // Set the layer indices
    if (currentPanelIndex == 0) {
        layeredPane.setLayer(p1, 0);
        layeredPane.setLayer(p2, -1);
        layeredPane.setLayer(p3, -1);
        layeredPane.setLayer(p4, -1);
        layeredPane.setLayer(p5, -1);
    } else if (currentPanelIndex == 1) {
        layeredPane.setLayer(p1, -1);
        layeredPane.setLayer(p2, 0);
        layeredPane.setLayer(p3, -1);
        layeredPane.setLayer(p4, -1);
        layeredPane.setLayer(p5, -1);
    } else if (currentPanelIndex == 2) {
        layeredPane.setLayer(p1, -1);
        layeredPane.setLayer(p2, -1);
        layeredPane.setLayer(p3, 0);
        layeredPane.setLayer(p4, -1);
        layeredPane.setLayer(p5, -1);
    } else if (currentPanelIndex == 3) {
        layeredPane.setLayer(p1, -1);
        layeredPane.setLayer(p2, -1);
        layeredPane.setLayer(p3, -1);
        layeredPane.setLayer(p4, 0);
        layeredPane.setLayer(p5, -1);
    } else if (currentPanelIndex == 4) {
        layeredPane.setLayer(p1, -1);
        layeredPane.setLayer(p2, -1);
        layeredPane.setLayer(p3, -1);
        layeredPane.setLayer(p4, -1);
        layeredPane.setLayer(p5, 0);
    }


       
    }//GEN-LAST:event_btnbackwardActionPerformed

    private void mlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mlogoutActionPerformed
        // TODO add your handling code here:
        User_Login loginForm = new User_Login();
                loginForm.setVisible(true);
                dispose(); 
    }//GEN-LAST:event_mlogoutActionPerformed

    private void mprofileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mprofileActionPerformed
        // TODO add your handling code here:
        Profile pform = new Profile();
                pform.setVisible(true);
                dispose(); 
    }//GEN-LAST:event_mprofileActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        User user=new User();
        user=UserDao.getUser(email);
        UserNameLabel.setText(user.getName());
        int i=1;
        //filling drinks table........
        DefaultTableModel dtmD = (DefaultTableModel) tDrinks.getModel();
        ArrayList<Item> item = ItemDao.getAllDrinks();
        Iterator<Item> itr = item.iterator();
         while(itr.hasNext()){
            Item in = itr.next();
            dtmD.addRow(new Object[]{i,in.getName(),in.getPrice()});
            i++;
        }
        //filling snacks table.....
        i=1;
        DefaultTableModel dtmS = (DefaultTableModel) tSnacks.getModel();
        ArrayList<Item> itemS = ItemDao.getAllSnacks();
        Iterator<Item> itrS = itemS.iterator();
         while(itrS.hasNext()){
            Item in = itrS.next();
            dtmS.addRow(new Object[]{i,in.getName(),in.getPrice()});
            i++;
        }
         //filling combos table......
        i=1;
        DefaultTableModel dtmC = (DefaultTableModel) tCombos.getModel();
        ArrayList<Item> itemC = ItemDao.getAllCombos();
        Iterator<Item> itrC = itemC.iterator();
         while(itrC.hasNext()){
            Item in = itrC.next();
            dtmC.addRow(new Object[]{i,in.getName(),in.getPrice()});
            i++;
        }
         
        
       
        
        
    }//GEN-LAST:event_formComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
//                new UserPopUpMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HelloLabel;
    private javax.swing.JLabel IconLabel;
    private javax.swing.JLabel TaglineLabel;
    private javax.swing.JLabel UserNameLabel;
    private javax.swing.JButton btnbackward;
    private javax.swing.JButton btnforward;
    private javax.swing.JButton btnusermenu;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLayeredPane layeredPane;
    private javax.swing.JMenuItem mgotocart;
    private javax.swing.JMenuItem mlogout;
    private javax.swing.JMenuItem mprofile;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel p5;
    private javax.swing.JPanel pcombo;
    private javax.swing.JPanel pdrinks;
    private javax.swing.JPanel poffers;
    private javax.swing.JPopupMenu popup;
    private javax.swing.JPanel psnacks;
    private javax.swing.JTable tCombos;
    private javax.swing.JTable tDrinks;
    private javax.swing.JTable tSnacks;
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
